Repository TNRIS/dataHub, pull requests merged in 2019-12, with the labels that each got.

#239 general sass and component cleanup; closing various issues
  src/components/CollectionFilterMap.jsx
  src/components/CollectionFilterMapView.jsx
  src/components/DialogTemplateListItems/CountyCoverage.jsx
  src/components/TnrisDownloadTemplate/TnrisDownloadTemplateDetails.jsx
  src/components/TnrisDownloadTemplate/TnrisDownloadTemplateDownload.jsx
  src/sass/_collectionFilterMapView.scss
  src/sass/_collectionTemplateDetails.scss
  src/sass/_collectionTemplates.scss
  src/sass/_contactTnrisForm.scss
  src/sass/_header.scss
  src/sass/_orderCart.scss
  src/sass/_orderTnrisDataForm.scss
  src/sass/_tnrisDownloadTemplateDownload.scss
Labels: UI/UX, bug, enhancement, frontend, ideas, mobile

#241 wms service component note re-wording
  src/components/DialogTemplateListItems/Services.jsx
Labels: enhancement, frontend

#242 Deselect county
  src/components/CollectionFilterMap.jsx
  src/components/CollectionFilterMapView.jsx
Labels: UI/UX, enhancement
